Staking rework
securesecrets/shadeswap pull request #87
Opened 2023-01-11 17:09 UTC by xucito

2023-01-13 19:29 UTC, FloppyDisck reviewed
Would it be possible to separate the staking math from the contract? That way the actual staking implementation is easier to review. This would make writing tests for the math easier too.

2023-01-13 19:29 UTC, FloppyDisck commented on contracts/staking/src/operations.rs
> +}
```suggestion
pub fn last_time_reward_applicable(
    current_timestamp: Uint128,
    valid_to: Uint128,
) -> Uint128 {
    max(current_timestamp, valid_to)
}
```

2023-01-13 19:33 UTC, FloppyDisck approved these changes

2023-01-13 19:55 UTC, DrPresident approved these changes
Rewards logic looks good, the data in the spreadsheet also looks to be accurate so as long as the tests reflect that data it should be good to go!

2023-01-13 20:06 UTC, GumboLimbo commented on contracts/staking/tests/integration.rs
> +    assert_eq!(balances.1, Uint128::new(15000));
Can you help me understand why the output is 15000? We are advancing 5000 seconds, there are 86400 seconds in a day, and the daily reward rate is 300000. Shouldn't the output be (5000 / 86400) * 300000 = 17361.11?

2023-01-13 20:18 UTC, DrPresident commented
Could we change the claimable function to reference `env.block.time` instead of a passed in timestamp?

2023-01-13 20:25 UTC, DrPresident requested changes
It seems the rewards rate is getting precision truncated during division, can we use the `x * 10^18` strategy to maintain that precision until we get to finalized token amounts? I believe this is causing slight yet significant truncation in rewards calculation (see alex's comment above)

2023-01-14 00:46 UTC, xucito commented
Have updated the logic now to use reward rate * 10^18. Also added claiming rewards if you unstake

2023-01-14 00:48 UTC, xucito commented on contracts/staking/tests/integration.rs
> +    assert_eq!(balances.1, Uint128::new(15000));
This was because of precision loss, has now been resolved

2023-01-14 00:51 UTC, xucito commented
> Could we change the claimable function to reference `env.block.time` instead of a passed in timestamp?

We could or we can pass contract_address instead of passing env. Prefer the latter as it makes it easier to test

2023-01-14 00:53 UTC, xucito commented on contracts/staking/src/operations.rs
> +}
Should this not be min?

2023-01-14 20:08 UTC, DrPresident commented
> > Could we change the claimable function to reference `env.block.time` instead of a passed in timestamp?
> 
> We could or we can pass contract_address instead of passing env. Prefer the latter as it makes it easier to test

What contract address would you pass in? I think in multi_test you can set manually set the timestamp for a block so you can just set the seconds to exactly what you want. I'll try to find an example I believe I have done it before.

2023-01-16 19:33 UTC, xucito commented
> > > Could we change the claimable function to reference `env.block.time` instead of a passed in timestamp?
> > 
> > 
> > We could or we can pass contract_address instead of passing env. Prefer the latter as it makes it easier to test
> 
> What contract address would you pass in? I think in multi_test you can set manually set the timestamp for a block so you can just set the seconds to exactly what you want. Example: https://github.com/securesecrets/shade/blob/a797ca47e23b549fb3a47fd506322587e90ab062/contracts/dao/treasury/tests/integration/allowance.rs#L32

We use .env to just get the contract address, either way its fine

2023-01-17 16:58 UTC, DrPresident approved these changes

2023-01-18 00:05 UTC, GumboLimbo approved these changes

2023-01-18 15:04 UTC, merged